server:
  port: 8080
  error:
    include-stacktrace: ALWAYS

spase.client:
  gatewayHost: https://get_address_from_CIP_provider/gateway

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_SERVICE_URL:'http://localhost:8761/eureka/'}
