security:
  basic:
    enabled: false

info:
  app:
    name: spample-standalone

server:
  port: ${SERVER_PORT:80}

feign.httpclient.enabled: false

logging:
  level:
    root: INFO
    feign: DEBUG

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI: mongodb://127.0.0.1:27017/spample}
    redis:
      repositories.enabled: false
  redis:
    host: ${REDIS_HOST: 127.0.0.1}
    port: ${REDIS_HOST: 6379}
  profiles:
    active: production
