security:
  basic:
    enabled: false

info:
  app:
    name: spample-standalone

server:
  port: ${SERVER_PORT:80}

feign.httpclient.enabled: false

logging:
  level:
    root: INFO
    feign: DEBUG

spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/spample
    redis:
      repositories.enabled: false
  redis:
    host: 127.0.0.1
    port: 6379
  profiles:
    active: production
