version: '3'
services:

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
